"use client";

import { useState } from "react";

type Result = { id:string; gradeLevel:string; learningArea:string; quarter?:string|null; competency:string; source:string; sourceUrl?:string|null; verified:boolean };

export default function CurriculumPage() {
  const [q,setQ]=useState(""); const [gradeLevel,setGradeLevel]=useState(""); const [learningArea,setLearningArea]=useState(""); const [results,setResults]=useState<Result[]>([]); const [status,setStatus]=useState("");
  async function search(){ setStatus("Searching verified curriculum..."); const p=new URLSearchParams(); if(q)p.set("q",q); if(gradeLevel)p.set("gradeLevel",gradeLevel); if(learningArea)p.set("learningArea",learningArea); const r=await fetch(`/api/curriculum/search?${p}`); const d=await r.json().catch(()=>({})); if(!r.ok){setStatus(d.error||"Unable to search curriculum.");return;} setResults(d.results||[]); setStatus(`${(d.results||[]).length} verified result(s) found.`); }
  return <main className="main"><div className="header"><div><div className="eyebrow">Curriculum Knowledge</div><h1>Find verified competencies.</h1><p className="subtitle">Search curriculum records that have source provenance. CoTeacher will never present AI guesses as official curriculum content.</p></div></div><section className="card"><div className="profile-form compact-form"><label>Search competency<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search competency or learning area"/></label><label>Grade level<input value={gradeLevel} onChange={e=>setGradeLevel(e.target.value)} placeholder="e.g. Grade 7"/></label><label>Learning area<input value={learningArea} onChange={e=>setLearningArea(e.target.value)} placeholder="e.g. Mathematics"/></label><button className="primary-button" onClick={search}>Search verified curriculum</button>{status&&<p className="form-status" role="status">{status}</p>}</div></section><section className="card"><div className="card-title"><h2>Verified results</h2></div>{results.length?results.map(item=><article className="curriculum-result" key={item.id}><div><strong>{item.gradeLevel} · {item.learningArea}</strong>{item.quarter&&<span> · {item.quarter}</span>}<p>{item.competency}</p><small>Source: {item.source}{item.sourceUrl?` · ${item.sourceUrl}`:""}</small></div><span className="verified-badge">Verified</span></article>):<div className="empty-state"><h3>No verified records available</h3><p>Results appear only after curriculum records are imported and verified. AI-generated competencies are intentionally excluded.</p></div>}</section></main>;
}
